<?php

namespace App\Widgets;

use CRUDBooster;
use DB;

/**
 *  |--------------------------------------------------------------------------
 *  |   You can use the below snippets to override the defaults.
 *  |====== Remove this doc block if you don't need it ========
 *  |--------------------------------------------------------------------------
 *  | public $controller = App/classPath/MyWidget::class; (optional)
 *  | public $presenter = App/classPath/WidgetPresenter::class; (optional)
 *  | public $minifyOutput = true; (use it to override the default value in config file)
 *  | public $cacheLifeTime = 0;   (use it to override the default value in config file)
 *  | public $contextAs = '$data'; (Default is : '$data')
 *  | public $template; (optional) (By default it looks for the view file generated by artisan)
 *  | public $cacheTags = []; (optional) (Not available for 'file system' cache driver)
 *  |--------------------------------------------------------------------------
 */
class DataPekerjaan
{
   /**
    * You may call this widget in any blade files like this :
    *
    * @widget('DataJabatan', ['a' => 'someVal', 'b' => 'foo'])
    */
	public function data($id)
	{
        $data = DB::table('data_pekerjaan')
                        ->leftJoin('geo_provinces', 'geo_provinces.id', '=', 'data_pekerjaan.propinsi_id')
                        ->leftJoin('geo_regencies', 'geo_regencies.id', '=', 'data_pekerjaan.kabupaten_id')
                        ->leftJoin('geo_districts', 'geo_districts.id', '=', 'data_pekerjaan.kecamatan_id')
                        ->leftJoin('geo_villages', 'geo_villages.id', '=', 'data_pekerjaan.desa_id')
                        ->select('data_pekerjaan.*','geo_provinces.name as province',
                             'geo_regencies.name as regency', 'geo_districts.name as district',
                             'geo_villages.name as village')
                        ->where('sertifikasi_id',$id)
                        ->first();
        return $data;
	}


   /**
    * By default the cacheKey of your widget output does not
    * depend on any Global variables like $_GET. So if the final
    * widget output depend on them you should return them here.
    * otherwise you get undesired results out of the cache store.
    */
	public function extraCacheKeyDependency()
	{
        return [];
	}

    public $template='data.jabatan';

}
