<?php

namespace App\Widgets;

use CRUDBooster;
use DB;

/**
 *  |--------------------------------------------------------------------------
 *  |   You can use the below snippets to override the defaults.
 *  |====== Remove this doc block if you don't need it ========
 *  |--------------------------------------------------------------------------
 *  | public $controller = App/classPath/MyWidget::class; (optional)
 *  | public $presenter = App/classPath/WidgetPresenter::class; (optional)
 *  | public $minifyOutput = true; (use it to override the default value in config file)
 *  | public $cacheLifeTime = 0;   (use it to override the default value in config file)
 *  | public $contextAs = '$data'; (Default is : '$data')
 *  | public $template; (optional) (By default it looks for the view file generated by artisan)
 *  | public $cacheTags = []; (optional) (Not available for 'file system' cache driver)
 *  |--------------------------------------------------------------------------
 */
class DataPribadi
{
   /**
    * You may call this widget in any blade files like this :
    *
    * @widget('DataPribadi', ['a' => 'someVal', 'b' => 'foo'])
    */


	public function data($id)
	{
        $data = DB::table('data_sertifikasi')
                    ->leftJoin('cms_users', 'cms_users.id', '=', 'data_sertifikasi.user_id')
                    ->leftJoin('data_pribadi', 'data_sertifikasi.id', '=', 'data_pribadi.sertifikasi_id')
                    ->leftJoin('geo_provinces', 'geo_provinces.id', '=', 'data_pribadi.province_id')
                    ->leftJoin('geo_regencies', 'geo_regencies.id', '=', 'data_pribadi.regency_id')
                    ->leftJoin('geo_districts', 'geo_districts.id', '=', 'data_pribadi.district_id')
                    ->leftJoin('geo_villages', 'geo_villages.id', '=', 'data_pribadi.village_id')
                    ->leftJoin('dokumen_sertifikasi', 'data_sertifikasi.id', '=', 'dokumen_sertifikasi.sertifikasi_id')
                    ->select('data_sertifikasi.*','data_pribadi.*','geo_provinces.name as province',
                             'geo_regencies.name as regency', 'geo_districts.name as district',
                             'geo_villages.name as village', 'cms_users.email', 'dokumen_sertifikasi.photo')
                    ->where('data_sertifikasi.id',$id)
                    ->first();

        //  dd($data);       
                    
        return $data;
	}


   /**
    * By default the cacheKey of your widget output does not
    * depend on any Global variables like $_GET. So if the final
    * widget output depend on them you should return them here.
    * otherwise you get undesired results out of the cache store.
    */
	public function extraCacheKeyDependency()
	{
        return [];
	}

    public $template='data.pribadi';
}
